// app/layout.js
import localFont from "next/font/local";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import HeaderComponent from "../components/header/HeaderComponent";
import FooterComponent from "../components/footer/FooterComponent";
import PasskeyLayout from "@/components/common/PasskeyLayout";
import Providers from "./Providers";

const patung = localFont({
  src: "./font/Patung.woff",
  variable: "--font-patung",
});

const interTight = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-inter-tight",
});

export const metadata = {
  title: "Seroclinix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${patung.variable}
          ${interTight.variable}
          antialiased
        `}
      >
        <Providers>
          <HeaderComponent />
          {children}
          <FooterComponent />
        </Providers>
        {/* <PasskeyLayout>
        </PasskeyLayout> */}
      </body>
    </html>
  );
}
